sudo: true
dist: trusty
language: node_js
node_js:
- '6'
before_script:
- npm install -g bower
- yarn
- bower install
script: gulp test
cache:
 directories:
 - node_modules
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
